<?xml version="1.0" encoding="utf-8"?>
<Database Name="TransRD" Class="TransRDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Boleto" Member="Boletos">
    <Type Name="Boleto">
      <Column Name="boleto_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viaje_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_compra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Viaje_Boleto" Member="Viaje" ThisKey="viaje_id" OtherKey="viaje_id" Type="Viaje" IsForeignKey="true" />
      <Association Name="Usuario_Boleto" Member="Usuario" ThisKey="usuario_id" OtherKey="usuario_id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Viaje" Member="Viajes">
    <Type Name="Viaje">
      <Column Name="viaje_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tipo_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="origen_lat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="origen_lng" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="destino_lat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="destino_lng" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="fecha_inicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecha_fin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="costo" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Ubicacion_actual" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Destino" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="Viaje_Boleto" Member="Boletos" ThisKey="viaje_id" OtherKey="viaje_id" Type="Boleto" />
      <Association Name="TipoTransporte_Viaje" Member="TipoTransporte" ThisKey="tipo_id" OtherKey="tipo_id" Type="TipoTransporte" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Usuario_Viaje" Member="Usuario" ThisKey="usuario_id" OtherKey="usuario_id" Type="Usuario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CodigoQR" Member="CodigoQRs">
    <Type Name="CodigoQR">
      <Column Name="qr_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cuenta_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valor_qr" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_creacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="valido_hasta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CuentaSaldo_CodigoQR" Member="CuentaSaldo" ThisKey="cuenta_id" OtherKey="cuenta_id" Type="CuentaSaldo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConfiguracionTarifas" Member="ConfiguracionTarifas">
    <Type Name="ConfiguracionTarifa">
      <Column Name="config_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tipo_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tarifa" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="vigente_desde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="vigente_hasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="TipoTransporte_ConfiguracionTarifa" Member="TipoTransporte" ThisKey="tipo_id" OtherKey="tipo_id" Type="TipoTransporte" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CuentaSaldo" Member="CuentaSaldos">
    <Type Name="CuentaSaldo">
      <Column Name="cuenta_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="saldo_actual" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_actualizacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CuentaSaldo_CodigoQR" Member="CodigoQRs" ThisKey="cuenta_id" OtherKey="cuenta_id" Type="CodigoQR" />
      <Association Name="CuentaSaldo_Recarga" Member="Recargas" ThisKey="cuenta_id" OtherKey="cuenta_id" Type="Recarga" />
      <Association Name="Usuario_CuentaSaldo" Member="Usuario" ThisKey="usuario_id" OtherKey="usuario_id" Type="Usuario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recarga" Member="Recargas">
    <Type Name="Recarga">
      <Column Name="recarga_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cuenta_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="metodo_pago" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fecha_recarga" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CuentaSaldo_Recarga" Member="CuentaSaldo" ThisKey="cuenta_id" OtherKey="cuenta_id" Type="CuentaSaldo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoTransporte" Member="TipoTransportes">
    <Type Name="TipoTransporte">
      <Column Name="tipo_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tarifa_base" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="TipoTransporte_Viaje" Member="Viajes" ThisKey="tipo_id" OtherKey="tipo_id" Type="Viaje" />
      <Association Name="TipoTransporte_ConfiguracionTarifa" Member="ConfiguracionTarifas" ThisKey="tipo_id" OtherKey="tipo_id" Type="ConfiguracionTarifa" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="usuario_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="contraseña" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="foto" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="roles" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Usuario_Boleto" Member="Boletos" ThisKey="usuario_id" OtherKey="usuario_id" Type="Boleto" />
      <Association Name="Usuario_Viaje" Member="Viajes" ThisKey="usuario_id" OtherKey="usuario_id" Type="Viaje" />
      <Association Name="Usuario_CuentaSaldo" Member="CuentaSaldos" ThisKey="usuario_id" OtherKey="usuario_id" Type="CuentaSaldo" />
    </Type>
  </Table>
</Database>