#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransporteDigitalRD.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TransRD")]
	public partial class TransRDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertBoleto(Boleto instance);
    partial void UpdateBoleto(Boleto instance);
    partial void DeleteBoleto(Boleto instance);
    partial void InsertViaje(Viaje instance);
    partial void UpdateViaje(Viaje instance);
    partial void DeleteViaje(Viaje instance);
    partial void InsertCodigoQR(CodigoQR instance);
    partial void UpdateCodigoQR(CodigoQR instance);
    partial void DeleteCodigoQR(CodigoQR instance);
    partial void InsertConfiguracionTarifa(ConfiguracionTarifa instance);
    partial void UpdateConfiguracionTarifa(ConfiguracionTarifa instance);
    partial void DeleteConfiguracionTarifa(ConfiguracionTarifa instance);
    partial void InsertCuentaSaldo(CuentaSaldo instance);
    partial void UpdateCuentaSaldo(CuentaSaldo instance);
    partial void DeleteCuentaSaldo(CuentaSaldo instance);
    partial void InsertRecarga(Recarga instance);
    partial void UpdateRecarga(Recarga instance);
    partial void DeleteRecarga(Recarga instance);
    partial void InsertTipoTransporte(TipoTransporte instance);
    partial void UpdateTipoTransporte(TipoTransporte instance);
    partial void DeleteTipoTransporte(TipoTransporte instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertTipoProblema(TipoProblema instance);
    partial void UpdateTipoProblema(TipoProblema instance);
    partial void DeleteTipoProblema(TipoProblema instance);
    partial void InsertReportarProblema(ReportarProblema instance);
    partial void UpdateReportarProblema(ReportarProblema instance);
    partial void DeleteReportarProblema(ReportarProblema instance);
    #endregion
		
		public TransRDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransRDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransRDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TransRDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Boleto> Boletos
		{
			get
			{
				return this.GetTable<Boleto>();
			}
		}
		
		public System.Data.Linq.Table<Viaje> Viajes
		{
			get
			{
				return this.GetTable<Viaje>();
			}
		}
		
		public System.Data.Linq.Table<CodigoQR> CodigoQRs
		{
			get
			{
				return this.GetTable<CodigoQR>();
			}
		}
		
		public System.Data.Linq.Table<ConfiguracionTarifa> ConfiguracionTarifas
		{
			get
			{
				return this.GetTable<ConfiguracionTarifa>();
			}
		}
		
		public System.Data.Linq.Table<CuentaSaldo> CuentaSaldos
		{
			get
			{
				return this.GetTable<CuentaSaldo>();
			}
		}
		
		public System.Data.Linq.Table<Recarga> Recargas
		{
			get
			{
				return this.GetTable<Recarga>();
			}
		}
		
		public System.Data.Linq.Table<TipoTransporte> TipoTransportes
		{
			get
			{
				return this.GetTable<TipoTransporte>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<TipoProblema> TipoProblema
		{
			get
			{
				return this.GetTable<TipoProblema>();
			}
		}
		
		public System.Data.Linq.Table<ReportarProblema> ReportarProblema
		{
			get
			{
				return this.GetTable<ReportarProblema>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boleto")]
	public partial class Boleto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _boleto_id;
		
		private int _usuario_id;
		
		private int _viaje_id;
		
		private System.Nullable<System.DateTime> _fecha_compra;
		
		private decimal _monto;
		
		private string _estado;
		
		private EntityRef<Viaje> _Viaje;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onboleto_idChanging(int value);
    partial void Onboleto_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void Onviaje_idChanging(int value);
    partial void Onviaje_idChanged();
    partial void Onfecha_compraChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_compraChanged();
    partial void OnmontoChanging(decimal value);
    partial void OnmontoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public Boleto()
		{
			this._Viaje = default(EntityRef<Viaje>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boleto_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int boleto_id
		{
			get
			{
				return this._boleto_id;
			}
			set
			{
				if ((this._boleto_id != value))
				{
					this.Onboleto_idChanging(value);
					this.SendPropertyChanging();
					this._boleto_id = value;
					this.SendPropertyChanged("boleto_id");
					this.Onboleto_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viaje_id", DbType="Int NOT NULL")]
		public int viaje_id
		{
			get
			{
				return this._viaje_id;
			}
			set
			{
				if ((this._viaje_id != value))
				{
					if (this._Viaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onviaje_idChanging(value);
					this.SendPropertyChanging();
					this._viaje_id = value;
					this.SendPropertyChanged("viaje_id");
					this.Onviaje_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_compra", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_compra
		{
			get
			{
				return this._fecha_compra;
			}
			set
			{
				if ((this._fecha_compra != value))
				{
					this.Onfecha_compraChanging(value);
					this.SendPropertyChanging();
					this._fecha_compra = value;
					this.SendPropertyChanged("fecha_compra");
					this.Onfecha_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Decimal(10,2) NOT NULL")]
		public decimal monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Boleto", Storage="_Viaje", ThisKey="viaje_id", OtherKey="viaje_id", IsForeignKey=true)]
		public Viaje Viaje
		{
			get
			{
				return this._Viaje.Entity;
			}
			set
			{
				Viaje previousValue = this._Viaje.Entity;
				if (((previousValue != value) 
							|| (this._Viaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Viaje.Entity = null;
						previousValue.Boletos.Remove(this);
					}
					this._Viaje.Entity = value;
					if ((value != null))
					{
						value.Boletos.Add(this);
						this._viaje_id = value.viaje_id;
					}
					else
					{
						this._viaje_id = default(int);
					}
					this.SendPropertyChanged("Viaje");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Boleto", Storage="_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Boletos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Boletos.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Viaje")]
	public partial class Viaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _viaje_id;
		
		private int _usuario_id;
		
		private int _tipo_id;
		
		private System.Nullable<double> _origen_lat;
		
		private System.Nullable<double> _origen_lng;
		
		private System.Nullable<double> _destino_lat;
		
		private System.Nullable<double> _destino_lng;
		
		private System.Nullable<System.DateTime> _fecha_inicio;
		
		private System.Nullable<System.DateTime> _fecha_fin;
		
		private System.Nullable<decimal> _costo;
		
		private string _Ubicacion_actual;
		
		private string _Destino;
		
		private EntitySet<Boleto> _Boletos;
		
		private EntityRef<TipoTransporte> _TipoTransporte;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onviaje_idChanging(int value);
    partial void Onviaje_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void Ontipo_idChanging(int value);
    partial void Ontipo_idChanged();
    partial void Onorigen_latChanging(System.Nullable<double> value);
    partial void Onorigen_latChanged();
    partial void Onorigen_lngChanging(System.Nullable<double> value);
    partial void Onorigen_lngChanged();
    partial void Ondestino_latChanging(System.Nullable<double> value);
    partial void Ondestino_latChanged();
    partial void Ondestino_lngChanging(System.Nullable<double> value);
    partial void Ondestino_lngChanged();
    partial void Onfecha_inicioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_finChanged();
    partial void OncostoChanging(System.Nullable<decimal> value);
    partial void OncostoChanged();
    partial void OnUbicacion_actualChanging(string value);
    partial void OnUbicacion_actualChanged();
    partial void OnDestinoChanging(string value);
    partial void OnDestinoChanged();
    #endregion
		
		public Viaje()
		{
			this._Boletos = new EntitySet<Boleto>(new Action<Boleto>(this.attach_Boletos), new Action<Boleto>(this.detach_Boletos));
			this._TipoTransporte = default(EntityRef<TipoTransporte>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viaje_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int viaje_id
		{
			get
			{
				return this._viaje_id;
			}
			set
			{
				if ((this._viaje_id != value))
				{
					this.Onviaje_idChanging(value);
					this.SendPropertyChanging();
					this._viaje_id = value;
					this.SendPropertyChanged("viaje_id");
					this.Onviaje_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_id", DbType="Int NOT NULL")]
		public int tipo_id
		{
			get
			{
				return this._tipo_id;
			}
			set
			{
				if ((this._tipo_id != value))
				{
					if (this._TipoTransporte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontipo_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_id = value;
					this.SendPropertyChanged("tipo_id");
					this.Ontipo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origen_lat", DbType="Float")]
		public System.Nullable<double> origen_lat
		{
			get
			{
				return this._origen_lat;
			}
			set
			{
				if ((this._origen_lat != value))
				{
					this.Onorigen_latChanging(value);
					this.SendPropertyChanging();
					this._origen_lat = value;
					this.SendPropertyChanged("origen_lat");
					this.Onorigen_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origen_lng", DbType="Float")]
		public System.Nullable<double> origen_lng
		{
			get
			{
				return this._origen_lng;
			}
			set
			{
				if ((this._origen_lng != value))
				{
					this.Onorigen_lngChanging(value);
					this.SendPropertyChanging();
					this._origen_lng = value;
					this.SendPropertyChanged("origen_lng");
					this.Onorigen_lngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destino_lat", DbType="Float")]
		public System.Nullable<double> destino_lat
		{
			get
			{
				return this._destino_lat;
			}
			set
			{
				if ((this._destino_lat != value))
				{
					this.Ondestino_latChanging(value);
					this.SendPropertyChanging();
					this._destino_lat = value;
					this.SendPropertyChanged("destino_lat");
					this.Ondestino_latChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destino_lng", DbType="Float")]
		public System.Nullable<double> destino_lng
		{
			get
			{
				return this._destino_lng;
			}
			set
			{
				if ((this._destino_lng != value))
				{
					this.Ondestino_lngChanging(value);
					this.SendPropertyChanging();
					this._destino_lng = value;
					this.SendPropertyChanged("destino_lng");
					this.Ondestino_lngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this.OncostoChanging(value);
					this.SendPropertyChanging();
					this._costo = value;
					this.SendPropertyChanged("costo");
					this.OncostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion_actual", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Ubicacion_actual
		{
			get
			{
				return this._Ubicacion_actual;
			}
			set
			{
				if ((this._Ubicacion_actual != value))
				{
					this.OnUbicacion_actualChanging(value);
					this.SendPropertyChanging();
					this._Ubicacion_actual = value;
					this.SendPropertyChanged("Ubicacion_actual");
					this.OnUbicacion_actualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destino", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Destino
		{
			get
			{
				return this._Destino;
			}
			set
			{
				if ((this._Destino != value))
				{
					this.OnDestinoChanging(value);
					this.SendPropertyChanging();
					this._Destino = value;
					this.SendPropertyChanged("Destino");
					this.OnDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Viaje_Boleto", Storage="_Boletos", ThisKey="viaje_id", OtherKey="viaje_id")]
		public EntitySet<Boleto> Boletos
		{
			get
			{
				return this._Boletos;
			}
			set
			{
				this._Boletos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransporte_Viaje", Storage="_TipoTransporte", ThisKey="tipo_id", OtherKey="tipo_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TipoTransporte TipoTransporte
		{
			get
			{
				return this._TipoTransporte.Entity;
			}
			set
			{
				TipoTransporte previousValue = this._TipoTransporte.Entity;
				if (((previousValue != value) 
							|| (this._TipoTransporte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoTransporte.Entity = null;
						previousValue.Viajes.Remove(this);
					}
					this._TipoTransporte.Entity = value;
					if ((value != null))
					{
						value.Viajes.Add(this);
						this._tipo_id = value.tipo_id;
					}
					else
					{
						this._tipo_id = default(int);
					}
					this.SendPropertyChanged("TipoTransporte");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Viaje", Storage="_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Viajes.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Viajes.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boletos(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Viaje = this;
		}
		
		private void detach_Boletos(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Viaje = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CodigoQR")]
	public partial class CodigoQR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _qr_id;
		
		private int _cuenta_id;
		
		private string _valor_qr;
		
		private System.Nullable<System.DateTime> _fecha_creacion;
		
		private System.Nullable<System.DateTime> _valido_hasta;
		
		private string _estado;
		
		private EntityRef<CuentaSaldo> _CuentaSaldo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onqr_idChanging(int value);
    partial void Onqr_idChanged();
    partial void Oncuenta_idChanging(int value);
    partial void Oncuenta_idChanged();
    partial void Onvalor_qrChanging(string value);
    partial void Onvalor_qrChanged();
    partial void Onfecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_creacionChanged();
    partial void Onvalido_hastaChanging(System.Nullable<System.DateTime> value);
    partial void Onvalido_hastaChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public CodigoQR()
		{
			this._CuentaSaldo = default(EntityRef<CuentaSaldo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int qr_id
		{
			get
			{
				return this._qr_id;
			}
			set
			{
				if ((this._qr_id != value))
				{
					this.Onqr_idChanging(value);
					this.SendPropertyChanging();
					this._qr_id = value;
					this.SendPropertyChanged("qr_id");
					this.Onqr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta_id", DbType="Int NOT NULL")]
		public int cuenta_id
		{
			get
			{
				return this._cuenta_id;
			}
			set
			{
				if ((this._cuenta_id != value))
				{
					if (this._CuentaSaldo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncuenta_idChanging(value);
					this.SendPropertyChanging();
					this._cuenta_id = value;
					this.SendPropertyChanged("cuenta_id");
					this.Oncuenta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_qr", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string valor_qr
		{
			get
			{
				return this._valor_qr;
			}
			set
			{
				if ((this._valor_qr != value))
				{
					this.Onvalor_qrChanging(value);
					this.SendPropertyChanging();
					this._valor_qr = value;
					this.SendPropertyChanged("valor_qr");
					this.Onvalor_qrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_creacion
		{
			get
			{
				return this._fecha_creacion;
			}
			set
			{
				if ((this._fecha_creacion != value))
				{
					this.Onfecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_creacion = value;
					this.SendPropertyChanged("fecha_creacion");
					this.Onfecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valido_hasta", DbType="DateTime")]
		public System.Nullable<System.DateTime> valido_hasta
		{
			get
			{
				return this._valido_hasta;
			}
			set
			{
				if ((this._valido_hasta != value))
				{
					this.Onvalido_hastaChanging(value);
					this.SendPropertyChanging();
					this._valido_hasta = value;
					this.SendPropertyChanged("valido_hasta");
					this.Onvalido_hastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuentaSaldo_CodigoQR", Storage="_CuentaSaldo", ThisKey="cuenta_id", OtherKey="cuenta_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CuentaSaldo CuentaSaldo
		{
			get
			{
				return this._CuentaSaldo.Entity;
			}
			set
			{
				CuentaSaldo previousValue = this._CuentaSaldo.Entity;
				if (((previousValue != value) 
							|| (this._CuentaSaldo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuentaSaldo.Entity = null;
						previousValue.CodigoQRs.Remove(this);
					}
					this._CuentaSaldo.Entity = value;
					if ((value != null))
					{
						value.CodigoQRs.Add(this);
						this._cuenta_id = value.cuenta_id;
					}
					else
					{
						this._cuenta_id = default(int);
					}
					this.SendPropertyChanged("CuentaSaldo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConfiguracionTarifas")]
	public partial class ConfiguracionTarifa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _config_id;
		
		private int _tipo_id;
		
		private decimal _tarifa;
		
		private System.Nullable<System.DateTime> _vigente_desde;
		
		private System.Nullable<System.DateTime> _vigente_hasta;
		
		private EntityRef<TipoTransporte> _TipoTransporte;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onconfig_idChanging(int value);
    partial void Onconfig_idChanged();
    partial void Ontipo_idChanging(int value);
    partial void Ontipo_idChanged();
    partial void OntarifaChanging(decimal value);
    partial void OntarifaChanged();
    partial void Onvigente_desdeChanging(System.Nullable<System.DateTime> value);
    partial void Onvigente_desdeChanged();
    partial void Onvigente_hastaChanging(System.Nullable<System.DateTime> value);
    partial void Onvigente_hastaChanged();
    #endregion
		
		public ConfiguracionTarifa()
		{
			this._TipoTransporte = default(EntityRef<TipoTransporte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_config_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int config_id
		{
			get
			{
				return this._config_id;
			}
			set
			{
				if ((this._config_id != value))
				{
					this.Onconfig_idChanging(value);
					this.SendPropertyChanging();
					this._config_id = value;
					this.SendPropertyChanged("config_id");
					this.Onconfig_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_id", DbType="Int NOT NULL")]
		public int tipo_id
		{
			get
			{
				return this._tipo_id;
			}
			set
			{
				if ((this._tipo_id != value))
				{
					if (this._TipoTransporte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontipo_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_id = value;
					this.SendPropertyChanged("tipo_id");
					this.Ontipo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarifa", DbType="Decimal(10,2) NOT NULL")]
		public decimal tarifa
		{
			get
			{
				return this._tarifa;
			}
			set
			{
				if ((this._tarifa != value))
				{
					this.OntarifaChanging(value);
					this.SendPropertyChanging();
					this._tarifa = value;
					this.SendPropertyChanged("tarifa");
					this.OntarifaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigente_desde", DbType="Date")]
		public System.Nullable<System.DateTime> vigente_desde
		{
			get
			{
				return this._vigente_desde;
			}
			set
			{
				if ((this._vigente_desde != value))
				{
					this.Onvigente_desdeChanging(value);
					this.SendPropertyChanging();
					this._vigente_desde = value;
					this.SendPropertyChanged("vigente_desde");
					this.Onvigente_desdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigente_hasta", DbType="Date")]
		public System.Nullable<System.DateTime> vigente_hasta
		{
			get
			{
				return this._vigente_hasta;
			}
			set
			{
				if ((this._vigente_hasta != value))
				{
					this.Onvigente_hastaChanging(value);
					this.SendPropertyChanging();
					this._vigente_hasta = value;
					this.SendPropertyChanged("vigente_hasta");
					this.Onvigente_hastaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransporte_ConfiguracionTarifa", Storage="_TipoTransporte", ThisKey="tipo_id", OtherKey="tipo_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TipoTransporte TipoTransporte
		{
			get
			{
				return this._TipoTransporte.Entity;
			}
			set
			{
				TipoTransporte previousValue = this._TipoTransporte.Entity;
				if (((previousValue != value) 
							|| (this._TipoTransporte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoTransporte.Entity = null;
						previousValue.ConfiguracionTarifas.Remove(this);
					}
					this._TipoTransporte.Entity = value;
					if ((value != null))
					{
						value.ConfiguracionTarifas.Add(this);
						this._tipo_id = value.tipo_id;
					}
					else
					{
						this._tipo_id = default(int);
					}
					this.SendPropertyChanged("TipoTransporte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CuentaSaldo")]
	public partial class CuentaSaldo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cuenta_id;
		
		private int _usuario_id;
		
		private decimal _saldo_actual;
		
		private System.Nullable<System.DateTime> _fecha_actualizacion;
		
		private EntitySet<CodigoQR> _CodigoQRs;
		
		private EntitySet<Recarga> _Recargas;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncuenta_idChanging(int value);
    partial void Oncuenta_idChanged();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void Onsaldo_actualChanging(decimal value);
    partial void Onsaldo_actualChanged();
    partial void Onfecha_actualizacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_actualizacionChanged();
    #endregion
		
		public CuentaSaldo()
		{
			this._CodigoQRs = new EntitySet<CodigoQR>(new Action<CodigoQR>(this.attach_CodigoQRs), new Action<CodigoQR>(this.detach_CodigoQRs));
			this._Recargas = new EntitySet<Recarga>(new Action<Recarga>(this.attach_Recargas), new Action<Recarga>(this.detach_Recargas));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cuenta_id
		{
			get
			{
				return this._cuenta_id;
			}
			set
			{
				if ((this._cuenta_id != value))
				{
					this.Oncuenta_idChanging(value);
					this.SendPropertyChanging();
					this._cuenta_id = value;
					this.SendPropertyChanged("cuenta_id");
					this.Oncuenta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int NOT NULL")]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_actual", DbType="Decimal(10,2) NOT NULL")]
		public decimal saldo_actual
		{
			get
			{
				return this._saldo_actual;
			}
			set
			{
				if ((this._saldo_actual != value))
				{
					this.Onsaldo_actualChanging(value);
					this.SendPropertyChanging();
					this._saldo_actual = value;
					this.SendPropertyChanged("saldo_actual");
					this.Onsaldo_actualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_actualizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_actualizacion
		{
			get
			{
				return this._fecha_actualizacion;
			}
			set
			{
				if ((this._fecha_actualizacion != value))
				{
					this.Onfecha_actualizacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_actualizacion = value;
					this.SendPropertyChanged("fecha_actualizacion");
					this.Onfecha_actualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuentaSaldo_CodigoQR", Storage="_CodigoQRs", ThisKey="cuenta_id", OtherKey="cuenta_id")]
		public EntitySet<CodigoQR> CodigoQRs
		{
			get
			{
				return this._CodigoQRs;
			}
			set
			{
				this._CodigoQRs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuentaSaldo_Recarga", Storage="_Recargas", ThisKey="cuenta_id", OtherKey="cuenta_id")]
		public EntitySet<Recarga> Recargas
		{
			get
			{
				return this._Recargas;
			}
			set
			{
				this._Recargas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_CuentaSaldo", Storage="_Usuario", ThisKey="usuario_id", OtherKey="usuario_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.CuentaSaldos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.CuentaSaldos.Add(this);
						this._usuario_id = value.usuario_id;
					}
					else
					{
						this._usuario_id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CodigoQRs(CodigoQR entity)
		{
			this.SendPropertyChanging();
			entity.CuentaSaldo = this;
		}
		
		private void detach_CodigoQRs(CodigoQR entity)
		{
			this.SendPropertyChanging();
			entity.CuentaSaldo = null;
		}
		
		private void attach_Recargas(Recarga entity)
		{
			this.SendPropertyChanging();
			entity.CuentaSaldo = this;
		}
		
		private void detach_Recargas(Recarga entity)
		{
			this.SendPropertyChanging();
			entity.CuentaSaldo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recarga")]
	public partial class Recarga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _recarga_id;
		
		private int _cuenta_id;
		
		private decimal _monto;
		
		private string _metodo_pago;
		
		private System.Nullable<System.DateTime> _fecha_recarga;
		
		private EntityRef<CuentaSaldo> _CuentaSaldo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrecarga_idChanging(int value);
    partial void Onrecarga_idChanged();
    partial void Oncuenta_idChanging(int value);
    partial void Oncuenta_idChanged();
    partial void OnmontoChanging(decimal value);
    partial void OnmontoChanged();
    partial void Onmetodo_pagoChanging(string value);
    partial void Onmetodo_pagoChanged();
    partial void Onfecha_recargaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_recargaChanged();
    #endregion
		
		public Recarga()
		{
			this._CuentaSaldo = default(EntityRef<CuentaSaldo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recarga_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int recarga_id
		{
			get
			{
				return this._recarga_id;
			}
			set
			{
				if ((this._recarga_id != value))
				{
					this.Onrecarga_idChanging(value);
					this.SendPropertyChanging();
					this._recarga_id = value;
					this.SendPropertyChanged("recarga_id");
					this.Onrecarga_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta_id", DbType="Int NOT NULL")]
		public int cuenta_id
		{
			get
			{
				return this._cuenta_id;
			}
			set
			{
				if ((this._cuenta_id != value))
				{
					if (this._CuentaSaldo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncuenta_idChanging(value);
					this.SendPropertyChanging();
					this._cuenta_id = value;
					this.SendPropertyChanged("cuenta_id");
					this.Oncuenta_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Decimal(10,2) NOT NULL")]
		public decimal monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metodo_pago", DbType="NVarChar(50)")]
		public string metodo_pago
		{
			get
			{
				return this._metodo_pago;
			}
			set
			{
				if ((this._metodo_pago != value))
				{
					this.Onmetodo_pagoChanging(value);
					this.SendPropertyChanging();
					this._metodo_pago = value;
					this.SendPropertyChanged("metodo_pago");
					this.Onmetodo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_recarga", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_recarga
		{
			get
			{
				return this._fecha_recarga;
			}
			set
			{
				if ((this._fecha_recarga != value))
				{
					this.Onfecha_recargaChanging(value);
					this.SendPropertyChanging();
					this._fecha_recarga = value;
					this.SendPropertyChanged("fecha_recarga");
					this.Onfecha_recargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CuentaSaldo_Recarga", Storage="_CuentaSaldo", ThisKey="cuenta_id", OtherKey="cuenta_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CuentaSaldo CuentaSaldo
		{
			get
			{
				return this._CuentaSaldo.Entity;
			}
			set
			{
				CuentaSaldo previousValue = this._CuentaSaldo.Entity;
				if (((previousValue != value) 
							|| (this._CuentaSaldo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CuentaSaldo.Entity = null;
						previousValue.Recargas.Remove(this);
					}
					this._CuentaSaldo.Entity = value;
					if ((value != null))
					{
						value.Recargas.Add(this);
						this._cuenta_id = value.cuenta_id;
					}
					else
					{
						this._cuenta_id = default(int);
					}
					this.SendPropertyChanged("CuentaSaldo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoTransporte")]
	public partial class TipoTransporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tipo_id;
		
		private string _nombre;
		
		private decimal _tarifa_base;
		
		private EntitySet<Viaje> _Viajes;
		
		private EntitySet<ConfiguracionTarifa> _ConfiguracionTarifas;
		
		private EntitySet<ReportarProblema> _ReportarProblema;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontipo_idChanging(int value);
    partial void Ontipo_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ontarifa_baseChanging(decimal value);
    partial void Ontarifa_baseChanged();
    #endregion
		
		public TipoTransporte()
		{
			this._Viajes = new EntitySet<Viaje>(new Action<Viaje>(this.attach_Viajes), new Action<Viaje>(this.detach_Viajes));
			this._ConfiguracionTarifas = new EntitySet<ConfiguracionTarifa>(new Action<ConfiguracionTarifa>(this.attach_ConfiguracionTarifas), new Action<ConfiguracionTarifa>(this.detach_ConfiguracionTarifas));
			this._ReportarProblema = new EntitySet<ReportarProblema>(new Action<ReportarProblema>(this.attach_ReportarProblema), new Action<ReportarProblema>(this.detach_ReportarProblema));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tipo_id
		{
			get
			{
				return this._tipo_id;
			}
			set
			{
				if ((this._tipo_id != value))
				{
					this.Ontipo_idChanging(value);
					this.SendPropertyChanging();
					this._tipo_id = value;
					this.SendPropertyChanged("tipo_id");
					this.Ontipo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarifa_base", DbType="Decimal(10,2) NOT NULL")]
		public decimal tarifa_base
		{
			get
			{
				return this._tarifa_base;
			}
			set
			{
				if ((this._tarifa_base != value))
				{
					this.Ontarifa_baseChanging(value);
					this.SendPropertyChanging();
					this._tarifa_base = value;
					this.SendPropertyChanged("tarifa_base");
					this.Ontarifa_baseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransporte_Viaje", Storage="_Viajes", ThisKey="tipo_id", OtherKey="tipo_id")]
		public EntitySet<Viaje> Viajes
		{
			get
			{
				return this._Viajes;
			}
			set
			{
				this._Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransporte_ConfiguracionTarifa", Storage="_ConfiguracionTarifas", ThisKey="tipo_id", OtherKey="tipo_id")]
		public EntitySet<ConfiguracionTarifa> ConfiguracionTarifas
		{
			get
			{
				return this._ConfiguracionTarifas;
			}
			set
			{
				this._ConfiguracionTarifas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransporte_ReportarProblema", Storage="_ReportarProblema", ThisKey="tipo_id", OtherKey="TipoTransporteId")]
		public EntitySet<ReportarProblema> ReportarProblema
		{
			get
			{
				return this._ReportarProblema;
			}
			set
			{
				this._ReportarProblema.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Viajes(Viaje entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransporte = this;
		}
		
		private void detach_Viajes(Viaje entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransporte = null;
		}
		
		private void attach_ConfiguracionTarifas(ConfiguracionTarifa entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransporte = this;
		}
		
		private void detach_ConfiguracionTarifas(ConfiguracionTarifa entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransporte = null;
		}
		
		private void attach_ReportarProblema(ReportarProblema entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransporte = this;
		}
		
		private void detach_ReportarProblema(ReportarProblema entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransporte = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usuario_id;
		
		private string _nombre;
		
		private string _email;
		
		private string _contraseña;
		
		private string _telefono;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private string _estado;
		
		private string _foto;
		
		private string _roles;
		
		private EntitySet<Boleto> _Boletos;
		
		private EntitySet<Viaje> _Viajes;
		
		private EntitySet<CuentaSaldo> _CuentaSaldos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusuario_idChanging(int value);
    partial void Onusuario_idChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OnfotoChanging(string value);
    partial void OnfotoChanged();
    partial void OnrolesChanging(string value);
    partial void OnrolesChanged();
    #endregion
		
		public Usuario()
		{
			this._Boletos = new EntitySet<Boleto>(new Action<Boleto>(this.attach_Boletos), new Action<Boleto>(this.detach_Boletos));
			this._Viajes = new EntitySet<Viaje>(new Action<Viaje>(this.attach_Viajes), new Action<Viaje>(this.detach_Viajes));
			this._CuentaSaldos = new EntitySet<CuentaSaldo>(new Action<CuentaSaldo>(this.attach_CuentaSaldos), new Action<CuentaSaldo>(this.detach_CuentaSaldos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto", DbType="NVarChar(500)")]
		public string foto
		{
			get
			{
				return this._foto;
			}
			set
			{
				if ((this._foto != value))
				{
					this.OnfotoChanging(value);
					this.SendPropertyChanging();
					this._foto = value;
					this.SendPropertyChanged("foto");
					this.OnfotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roles", DbType="NVarChar(200)")]
		public string roles
		{
			get
			{
				return this._roles;
			}
			set
			{
				if ((this._roles != value))
				{
					this.OnrolesChanging(value);
					this.SendPropertyChanging();
					this._roles = value;
					this.SendPropertyChanged("roles");
					this.OnrolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Boleto", Storage="_Boletos", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<Boleto> Boletos
		{
			get
			{
				return this._Boletos;
			}
			set
			{
				this._Boletos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Viaje", Storage="_Viajes", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<Viaje> Viajes
		{
			get
			{
				return this._Viajes;
			}
			set
			{
				this._Viajes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_CuentaSaldo", Storage="_CuentaSaldos", ThisKey="usuario_id", OtherKey="usuario_id")]
		public EntitySet<CuentaSaldo> CuentaSaldos
		{
			get
			{
				return this._CuentaSaldos;
			}
			set
			{
				this._CuentaSaldos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boletos(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Boletos(Boleto entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Viajes(Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Viajes(Viaje entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_CuentaSaldos(CuentaSaldo entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_CuentaSaldos(CuentaSaldo entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoProblema")]
	public partial class TipoProblema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private EntitySet<ReportarProblema> _ReportarProblema;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TipoProblema()
		{
			this._ReportarProblema = new EntitySet<ReportarProblema>(new Action<ReportarProblema>(this.attach_ReportarProblema), new Action<ReportarProblema>(this.detach_ReportarProblema));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoProblema_ReportarProblema", Storage="_ReportarProblema", ThisKey="Id", OtherKey="TipoProblemaId")]
		public EntitySet<ReportarProblema> ReportarProblema
		{
			get
			{
				return this._ReportarProblema;
			}
			set
			{
				this._ReportarProblema.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ReportarProblema(ReportarProblema entity)
		{
			this.SendPropertyChanging();
			entity.TipoProblema = this;
		}
		
		private void detach_ReportarProblema(ReportarProblema entity)
		{
			this.SendPropertyChanging();
			entity.TipoProblema = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportarProblema")]
	public partial class ReportarProblema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _TipoProblemaId;
		
		private int _TipoTransporteId;
		
		private double _Origen_Lat;
		
		private double _Origen_Lng;
		
		private string _Desc_Problema;
		
		private EntityRef<TipoProblema> _TipoProblema;
		
		private EntityRef<TipoTransporte> _TipoTransporte;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTipoProblemaIdChanging(int value);
    partial void OnTipoProblemaIdChanged();
    partial void OnTipoTransporteIdChanging(int value);
    partial void OnTipoTransporteIdChanged();
    partial void OnOrigen_LatChanging(double value);
    partial void OnOrigen_LatChanged();
    partial void OnOrigen_LngChanging(double value);
    partial void OnOrigen_LngChanged();
    partial void OnDesc_ProblemaChanging(string value);
    partial void OnDesc_ProblemaChanged();
    #endregion
		
		public ReportarProblema()
		{
			this._TipoProblema = default(EntityRef<TipoProblema>);
			this._TipoTransporte = default(EntityRef<TipoTransporte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProblemaId", DbType="Int NOT NULL")]
		public int TipoProblemaId
		{
			get
			{
				return this._TipoProblemaId;
			}
			set
			{
				if ((this._TipoProblemaId != value))
				{
					if (this._TipoProblema.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoProblemaIdChanging(value);
					this.SendPropertyChanging();
					this._TipoProblemaId = value;
					this.SendPropertyChanged("TipoProblemaId");
					this.OnTipoProblemaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoTransporteId", DbType="Int NOT NULL")]
		public int TipoTransporteId
		{
			get
			{
				return this._TipoTransporteId;
			}
			set
			{
				if ((this._TipoTransporteId != value))
				{
					if (this._TipoTransporte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoTransporteIdChanging(value);
					this.SendPropertyChanging();
					this._TipoTransporteId = value;
					this.SendPropertyChanged("TipoTransporteId");
					this.OnTipoTransporteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen_Lat", DbType="Float NOT NULL")]
		public double Origen_Lat
		{
			get
			{
				return this._Origen_Lat;
			}
			set
			{
				if ((this._Origen_Lat != value))
				{
					this.OnOrigen_LatChanging(value);
					this.SendPropertyChanging();
					this._Origen_Lat = value;
					this.SendPropertyChanged("Origen_Lat");
					this.OnOrigen_LatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen_Lng", DbType="Float NOT NULL")]
		public double Origen_Lng
		{
			get
			{
				return this._Origen_Lng;
			}
			set
			{
				if ((this._Origen_Lng != value))
				{
					this.OnOrigen_LngChanging(value);
					this.SendPropertyChanging();
					this._Origen_Lng = value;
					this.SendPropertyChanged("Origen_Lng");
					this.OnOrigen_LngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desc_Problema", DbType="VarChar(300)")]
		public string Desc_Problema
		{
			get
			{
				return this._Desc_Problema;
			}
			set
			{
				if ((this._Desc_Problema != value))
				{
					this.OnDesc_ProblemaChanging(value);
					this.SendPropertyChanging();
					this._Desc_Problema = value;
					this.SendPropertyChanged("Desc_Problema");
					this.OnDesc_ProblemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoProblema_ReportarProblema", Storage="_TipoProblema", ThisKey="TipoProblemaId", OtherKey="Id", IsForeignKey=true)]
		public TipoProblema TipoProblema
		{
			get
			{
				return this._TipoProblema.Entity;
			}
			set
			{
				TipoProblema previousValue = this._TipoProblema.Entity;
				if (((previousValue != value) 
							|| (this._TipoProblema.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoProblema.Entity = null;
						previousValue.ReportarProblema.Remove(this);
					}
					this._TipoProblema.Entity = value;
					if ((value != null))
					{
						value.ReportarProblema.Add(this);
						this._TipoProblemaId = value.Id;
					}
					else
					{
						this._TipoProblemaId = default(int);
					}
					this.SendPropertyChanged("TipoProblema");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransporte_ReportarProblema", Storage="_TipoTransporte", ThisKey="TipoTransporteId", OtherKey="tipo_id", IsForeignKey=true)]
		public TipoTransporte TipoTransporte
		{
			get
			{
				return this._TipoTransporte.Entity;
			}
			set
			{
				TipoTransporte previousValue = this._TipoTransporte.Entity;
				if (((previousValue != value) 
							|| (this._TipoTransporte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoTransporte.Entity = null;
						previousValue.ReportarProblema.Remove(this);
					}
					this._TipoTransporte.Entity = value;
					if ((value != null))
					{
						value.ReportarProblema.Add(this);
						this._TipoTransporteId = value.tipo_id;
					}
					else
					{
						this._TipoTransporteId = default(int);
					}
					this.SendPropertyChanged("TipoTransporte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
